streamforward:
  container_name: streamforward
  image: simonlerpard/streamforward
  cap_add:
    - NET_ADMIN
  ports:
     - 32400:32400
     - 3000:3000
  environment:
    DESTINATION_IP: 192.168.1.24
    DESTINATION_PORT: 32400
    DEFAULT_TIMEOUT: 60 # in seconds
